export const destinations = Array.from(
  new Set([
    "Porto Alegre, Brazil",
    "Paris, France",
    "Tokyo, Japan",
    "New York, USA",
    "Sydney, Australia",
    "Barcelona, Spain",
    "Berlin, Germany",
    "Munich, Germany",
    "Rome, Italy",
    "Milan, Italy",
    "London, United Kingdom",
    "Manchester, United Kingdom",
    "Madrid, Spain",
    "Valencia, Spain",
    "Lisbon, Portugal",
    "Porto, Portugal",
    "Vienna, Austria",
    "Salzburg, Austria",
    "Zurich, Switzerland",
    "Geneva, Switzerland",
    "Amsterdam, Netherlands",
    "Rotterdam, Netherlands",
    "Brussels, Belgium",
    "Antwerp, Belgium",
    "Los Angeles, USA",
    "San Francisco, USA",
    "Las Vegas, USA",
    "Miami, USA",
    "Orlando, USA",
    "Chicago, USA",
    "Washington D.C., USA",
    "Boston, USA",
    "Seattle, USA",
    "New Orleans, USA",
    "Auckland, New Zealand",
    "Wellington, New Zealand",
    "Christchurch, New Zealand",
    "Melbourne, Australia",
    "Brisbane, Australia",
    "Perth, Australia",
    "Cape Town, South Africa",
    "Johannesburg, South Africa",
    "Durban, South Africa",
    "Nairobi, Kenya",
    "Marrakech, Morocco",
    "Casablanca, Morocco",
    "Cairo, Egypt",
    "Buenos Aires, Argentina",
    "Santiago, Chile",
    "Lima, Peru",
    "Bogota, Colombia",
    "Quito, Ecuador",
    "Montevideo, Uruguay",
    "La Paz, Bolivia",
    "Dublin, Ireland",
  ])
);
